### ISSUE TITLE
Laravel 5.1 support?

### ISSUE THREAD

**Issue by tortuetorche** [laracasts/matryoshka#4]
Hi folks,

I see in the `composer.json` of this package that we need Laravel >= 5.2 as a minimum requirement to use it.
Is there any particular reason for this version constraint?
Can you also support Laravel 5.1 (which is a LTS release)?

Cheers,
Tortue Torche

**Comment by laracasts** [comment]
I'll need to have a look around, but I'm pretty sure we can bring that minimum down to 5.1.

**Comment by giacomo** [comment]
+1

**Comment by jonathanpmartins** [comment]
I'm sure it is much more easy to upgrade your project to Laravel 5.2. Look at the upgrade Guide, easy: https://laravel.com/docs/5.2/upgrade#upgrade-5.2.0
I upgrade it the next day of the official release. The project is a big one, and it takes 30-60 minutes to upgrade.

**Comment by tortuetorche** [comment]
Of course we can upgrade our projects to Laravel 5.2
But for big projects, I work only with Long Term Support releases.
I think they are made for this, otherwise I don't know why they exist :smirk_cat:

**Comment by selfeky** [comment]
Hey @tortuetorche 
Did you find a solution for this? Im using LTS as well

Thanks

**Comment by miloandco** [comment]
@laracasts  - any news regarding 5.1? :)

**Comment by laracasts** [comment]
It's open source. :) PRs welcomed.

**Comment by willvincent** [comment]
PR #11 extends support to both 5.1 and 5.3 :)
