### ISSUE TITLE
Can you support cache key for Collection?

### ISSUE THREAD

**Issue by tortuetorche** [laracasts/matryoshka#5]
Is it possible to add `getCacheKey()` to `Illuminate\Database\Eloquent\Builder` (or maybe `Illuminate\Support\Collection`)? Like Rails 5 does.

Example (ported from ruby code):

``` php
$users = \App\User::where('name', 'LIKE', '%Alberto%');// Or \App\User::where('name', 'LIKE', '%Alberto%')->get();
$users->getCacheKey();
=> "App\User/query-5942b155a43b139f2471b872ac54251f-3-20150714212107656125000"
```

References: 
- http://guides.rubyonrails.org/caching_with_rails.html#fragment-caching
- https://github.com/rails/rails/blob/29cf0dd/activerecord/lib/active_record/collection_cache_key.rb
- https://github.com/rails/rails/commit/476e3f5

**Comment by laracasts** [comment]
Yeah, this is definitely on my todo list. Just need to figure out how we'd specifically go about creating the key for an Eloquent collection.

**Comment by JeffreyWay** [comment]
I wonder if we can get away with this being the cache key for any collection:

```
"collection/App\Model/{{ $collection->count() }}-{{ $collection->max('updated_at') }}"
```

So basically "collection/model-name/collection-count-max-updated-at-timestamp"

I _think_ that would be enough? If the collection contents change, the cache will bust.

**Comment by tortuetorche** [comment]
Yep, but what about collection with `where` clause? We should use a query signature for them, isn't it?
See: https://github.com/rails/rails/blob/29cf0dd/activerecord/lib/active_record/collection_cache_key.rb#L5

**Comment by JeffreyWay** [comment]
I'm not sure what `collection.to_sql` would look translate to in our case, though. Hmm..

**Comment by tortuetorche** [comment]
I think we need to get the original Eloquent Builder instance from an Eloquent Collection.

Maybe we should add the [`Illuminate\Database\Eloquent\Collection::getQuery()`](https://github.com/laravel/framework/blob/5.2/src/Illuminate/Database/Eloquent/Collection.php) method, like this [one](https://github.com/laravel/framework/blob/v5.2.20/src/Illuminate/Database/Eloquent/Relations/Relation.php#L212).

And overrides the [`Illuminate\Database\Eloquent\Builder::get()`](https://github.com/laravel/framework/blob/v5.2.20/src/Illuminate/Database/Eloquent/Builder.php#L299) method to push the Eloquent Builder instance inside the Eloquent Collection.

Then we can do things like this:

``` php
$collection = \App\User::where('name', 'LIKE', '%Alberto%')->get();

// Inside a `Illuminate\Database\Eloquent\Collection::getCacheKey()` method:
// Get the original Eloquent Builder instance
$collectionQuery = $collection->getQuery();

// And we can access to the Eloquent Builder methods
$collectionQuery->toSql();
$collectionQuery->getBindings();
```

So this stuff will be really useful to get a query signature for caching purpose...

**Comment by tortuetorche** [comment]
:+1: I didn't test it yet but thank you for adding this feature!
